excluded:
  - Pods
  - fastlane
opt_in_rules:
  - convenience_type
  - empty_count
  - empty_string
  - fatal_error_message
  - first_where
  - modifier_order
  - toggle_bool
  - unused_declaration
  - overridden_super_call
type_name:
  excluded:
    - T
  allowed_symbols:
    - _Previews
identifier_name:
  excluded:
      - id
      - by