name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7.3'
    - name: Run SwiftLint
      uses: maierj/fastlane-action@v2.0.1
      with: 
        lane: 'lint'
        subdirectory: 'fastlane'

  test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7.3'
    - uses: AckeeCZ/load-xcode-version@1.0
    - name: Install Dependencies
      run: pod install --repo-update
    - name: Run UI Tests
      uses: maierj/fastlane-action@v2.0.1
      with: 
        lane: 'test'
        subdirectory: 'fastlane'

  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7.3'
    - uses: AckeeCZ/load-xcode-version@1.0
    - name: Install Dependencies
      run: pod install --repo-update
    - name: Build
      uses: maierj/fastlane-action@v2.0.1
      with: 
        lane: 'build'
        subdirectory: 'fastlane'